version: "3.9"
services:
  shoe-db:
    #docker run --name some-postgis -e POSTGRES_PASSWORD=mysecretpassword -d postgis/postgis
    container_name: shoe-db
    image: "postgis/postgis"
    env_file:
      - ./.env
    volumes:
      - ./db/sql/build_db.sql:/var/lib/pgsql/data/sql/build_db.sql
      - ./db/data/:/var/lib/pgsql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=TempS3cret
      - POSTGRES_USER=shoe_admin
      - POSTGRES_DB=shoebox
  shoe-api:
    container_name: shoe-api
    build:
      context: "./api"
      dockerfile: "Dockerfile"
    volumes:
      - ./api:/home/node/app
      # - ./api:/opt/app-root/src/api
    ports:
      - 8443:8443
    env_file:
      - ./.env
      - ./.env.local
    depends_on:
      - shoe-db
  shoe-client:
    container_name: shoe-client
    build:
      context: "./client"
      dockerfile: "Dockerfile"
    # volumes:
    #   - ./client:/opt/app-root/src/api
    user: "node"
    # working_dir: /home/node/app
    volumes:
      - ./client:/home/node/app
    ports:
      - 3000:3000
    # command: "npm start"
networks:
  default:
    name: shoe-network
    external: true
