version: "3.9"
services:
  shoe-db:
    #docker run --name some-postgis -e POSTGRES_PASSWORD=mysecretpassword -d postgis/postgis
    container_name: shoe-db
    image: "postgis/postgis"
    env_file:
      - ./.env
    volumes:
      - ./db/sql/build_db.sql:/var/lib/pgsql/data/sql/build_db.sql
      - ./db/data/:/var/lib/pgsql/data
    ports:
      -${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD=TempS3cret
      - POSTGRES_USER=shoe_admin
      - POSTGRES_DB=shoebox
  shoe-api:
    container_name: shoe-api
    build:
      context: "./api"
      dockerfile: "Dockerfile"
    volumes:
      - ./api:/opt/app-root/src/api
  shoe-client:
    container_name: shoe-client
    build:
      context: "./client"
      dockerfile: "Dockerfile"
    volumes:
      - ./client:/opt/app-root/src/api
networks:
  default:
    name: shoe-networks
    external: true
